export const AddUserDrawerBody = [
  {
    title: 'First Name',
    id: 'fistName',
    type: 'text',
    name: 'fistName',
    defaultValue: '',
    errorMessage: 'Please enter the first name',
    placeholder: 'Enter your first name',
  },
  {
    title: 'Last Name',
    id: 'lastName',
    type: 'text',
    name: 'lastName',
    defaultValue: '',
    errorMessage: 'Please enter the last name',
    placeholder: 'Enter your last name',
  },
  {
    title: 'Email Address',
    id: 'email',
    type: 'text',
    name: 'email',
    defaultValue: '',
    errorMessage: 'Please enter the email address',
    placeholder: 'Enter your email address',
  },
  {
    title: 'Phone Number',
    id: 'phoneNumber',
    type: 'number',
    name: 'phoneNumber',
    defaultValue: '',
    errorMessage: 'Please enter the phone number',
    placeholder: 'Enter your phone number',
  },
]